name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: " login to dockerhub"
        run: docker login --username ${{ secrets.DOCKERHUB_USERNAME}} --password ${{ secrets.DOCKERHUB_TOKEN }}
      - name: " building docker "
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME}}/java-docker-github-task:latest .
      - name: " pushing to docker hub "
        run: docker push ${{ secrets.DOCKERHUB_USERNAME}}/java-docker-github-task:latest