name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Will not download files on machine
      - name: "before printing the folder contents"
        run: ls

      # To download files using library or pre-built action
      - uses: actions/checkout@v3

      - name: "after printing the folder contents"
        run: ls -a
