name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
      - name: "Testing github actions"
        run: pwd
      - name: "Testing printing"
        run: echo My name is omar
